### ISSUE TITLE
What about Safari? Edge?

### ISSUE THREAD

**Issue by amazingrando** [sindresorhus/modern-normalize#11]
> Includes only normalizations for the latest Chrome and Firefox

What about Safari (macOS and iOS)? Edge?

**Comment by Pickra** [comment]
Curious about this too, as well as IE. I guess the package consumer is responsible for using something like autoprefixer or is it because of issue #2?

**Comment by amazingrando** [comment]
From @sindresorhus on [Designer News...](https://www.designernews.co/stories/91673-normalize-browsers-default-style)

> Both Edge and Safari are only rarely updated, and they're updated together with the operating system. Modern browsers auto-update themselves frequently. Those browsers also have such a small market share, so doesn't make sense to spend time on them. If you need to support them, you can use normalize.css.

**Comment by sindresorhus** [comment]
On further thought, I've decided to support latest Safari too because of iOS market share. IE and Edge will never be supported though.

**Comment by mikehaas763** [comment]
Screw IE, but Edge is decoupling updates from the OS updates (https://www.computerworld.com/article/3193871/microsoft-windows/microsoft-to-cut-update-ties-between-edge-and-windows-10.html) and is a pretty modern browser. Would you accept PRs to support Edge?

**Comment by keithjgrant** [comment]
Edge de-coupled from OS updates over nine months ago. Edge is an evergreen browser and should absolutely be included

**Comment by equinusocio** [comment]
Edge will be a chronium-based browser from 2019..so good move @sindresorhus 👍
