### ISSUE TITLE
Differences from normalize, 'Doesn't force font-family...' is no longer valid

### ISSUE THREAD

**Issue by lacymorrow** [sindresorhus/modern-normalize#14]
As of recent, Normalize.css now uses `font-family: inherit;` for input elements.

https://github.com/necolas/normalize.css/commit/ca8a357baf6e724ab84843ac4607f8d2024cf0f8

**Comment by paulirish** [comment]
(also it's dropped IE8/9 support, and is now roughly the same size (781 vs 697 gz bytes))

(and i suppose that means it's maintained again)

(turns out, reseting css has a history of [drama](https://github.com/necolas/normalize.css/issues/664))

(i've added to that drama, myself)

(<3z everyone)

**Comment by lacymorrow** [comment]
([definitely actively maintained](https://github.com/necolas/normalize.css/commit/4ab3de5bdd26b161c3c82a5a2f72df3e57a8e4bf))

(also <3z everyone)

**Comment by sindresorhus** [comment]
When I visited normalize.css the other day, the last commit was a year ago and it had many many open issues, but glad it's actively maintained again. I've updated the readme to reflect this.

**Comment by paulirish** [comment]
All good, amigo.
