### ISSUE TITLE
More accessible line height

### ISSUE THREAD

**Issue by lukasoppermann** [sindresorhus/modern-normalize#4]
Hey,
first of all, nice project.

I am just wonder why you set the line-height to 115% (https://github.com/sindresorhus/modern-normalize/blob/master/modern-normalize.css#L25)? Is it because the default leading for most browsers is between 110% to 120%?

The line height typically recommended in typography is 120–145%. Do you have a special reason? Otherwise I would recommend something like 130%, because it still looks nice, but greater leading is actually a good practise for accessibility. You could even go all the way up to 150% which is the recommended leading by the [W3C accessibility guidelines](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-visual-presentation.html).

I would think if we want to normalize, we could also try to normalize not just to the defaults, but also a little bit in the direction of an overall accessible web. Looking forward to your thoughts. 👋

**Comment by sindresorhus** [comment]
See discussion about it here: https://github.com/necolas/normalize.css/issues/612

**Comment by lukasoppermann** [comment]
So the argument is basically to go for "normal" as in what most browser doe and not for good? So you are basically saying this would be to opinionated?

**Comment by sindresorhus** [comment]
Yeah, the point is to normalize what browsers do, even if it's not so good. Making it better is a different problem and something I intend to solve with #13. I'll definitely improve the line height there.
