### ISSUE TITLE
1.1.0 is not available on cdnjs.com

### ISSUE THREAD

**Issue by EvgenyOrekhov** [sindresorhus/modern-normalize#52]
There is no version 1.1.0 on https://cdnjs.com/libraries/modern-normalize.

**Comment by sindresorhus** [comment]
I don't remember how CDN.js works. Whether they update automatically or if it has to be done manually by someone.

**Comment by EvgenyOrekhov** [comment]
Should be automatic. Created https://github.com/cdnjs/packages/issues/716.

**Comment by EvgenyOrekhov** [comment]
It's available now.

**Comment by quantuminformation** [comment]
Add cdn to the readme?
