### ISSUE TITLE
Fix Logo (transform text to shapes)

### ISSUE THREAD

**Issue by pedrogpimenta** [sindresorhus/modern-normalize#6]
The logo has render problems, as least on Firefox: 
![screenshot 2018-02-08 12 16 41](https://user-images.githubusercontent.com/869022/35970300-2768655e-0cca-11e8-95ec-266fc9c3c3f6.png)

While using SVG for a logo is great, when (or before) exporting, all text should be transformed to shapes so that the rendering is the same on each browser/viewer and don't depend on the text rendering machine.

**Comment by sindresorhus** [comment]
Ugh, I forgot to hide the original text. I had already created outlines on a new layer. And of course Chrome's text rendering is exactly the same as Sketch, so I didn't notice. Fixed by https://github.com/sindresorhus/modern-normalize/commit/8093d7803864792cff1e083f070159a7a2c11cac.
