### ISSUE TITLE
Move font-family to html from body

### ISSUE THREAD

**Issue by bes-internal** [sindresorhus/modern-normalize#70]
`font-family` styles should be placed as high up in the hierarchy as possible.
In many projects, fonts are installed for the whole site in html or in :root

**Comment by bes-internal** [comment]
I tested and smoke the documentation and it looks like we should use `html` (with specifity 0-0-1) because the specificity of `:root` is higher (0-1-0). That means the property rules declared under `:root` will take precedence over those under `html` even if it is later in the code.
Move to `html` please

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/modern-normalize/commit/b8025616e23c59f42ea1f9745a229d938eab9e33

**Comment by roydukkey** [comment]
🙃 Ping for a release of https://github.com/sindresorhus/modern-normalize/commit/b8025616e23c59f42ea1f9745a229d938eab9e33. Thanks.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/modern-normalize/releases/tag/v2.0.0
