### ISSUE TITLE
Compressed minified version is not that much smaller than normalize.css

### ISSUE THREAD

**Issue by Maxim-Mazurok** [sindresorhus/modern-normalize#74]
Hello!
Looks like a compressed and minified version of normalize.css is not that much bigger than a compressed and minified version of modern-normalize from the same CDN.
Comparing these two:
- https://cdn.jsdelivr.net/npm/normalize.css/normalize.min.css
- https://cdn.jsdelivr.net/npm/modern-normalize/modern-normalize.min.css

normalize.css compressed size ranges from 1.3kB to 1.7kB:
![image](https://github.com/sindresorhus/modern-normalize/assets/7756211/2d818451-fe59-4c8f-8ba5-e811efe69e34)

modern-normalize compressed size ranges from 1.3kB to 1.6kB:
![image](https://github.com/sindresorhus/modern-normalize/assets/7756211/51a76e44-73a4-443b-999c-3214c859b624)

I was expecting more size savings since that seems to be the main differentiator of this project.

There might be some CDN optimization in play, maybe they compress them differently (different algo or strength). Just sharing these results for people who are also trying to choose like I am. For me, the savings seem to be insignificant compared to a loss in older browser support.

**Comment by sindresorhus** [comment]
While we removed all workarounds for older browsers, we also added new workarounds for newer browsers that Normalize.css is missing. I think the main argument for this project is that it's actually maintained.

**Comment by sindresorhus** [comment]
> For me, the savings seem to be insignificant compared to a loss in older browser support.

The browser support you are talking about are browser versions no one should be supporting anyway (archaic versions). Mostly IE and ancient versions of Chrome and Firefox (which updates automatically).

**Comment by Maxim-Mazurok** [comment]
> While we removed all workarounds for older browsers, we also added new workarounds for newer browsers that Normalize.css is missing. I think the main argument for this project is that it's actually maintained.

Oh, right, now it makes sense, I didn't notice that last commit to normalize.css was 6 years ago...

> > For me, the savings seem to be insignificant compared to a loss in older browser support.
> 
> The browser support you are talking about are browser versions no one should be supporting anyway (archaic versions). Mostly IE and ancient versions of Chrome and Firefox (which updates automatically).

Yeah, it doesn't seem too important, but still might be corporate clients with lazy admins blocking updates and supplying older versions. But I guess styling consistency is not that big of a deal in this case as long as it's usable
