### ISSUE TITLE
Double "monospace" font-family

### ISSUE THREAD

**Issue by LasaleFamine** [sindresorhus/modern-normalize#8]
Here https://github.com/sindresorhus/modern-normalize/blob/master/modern-normalize.css#L67 and here https://github.com/sindresorhus/modern-normalize/blob/master/modern-normalize.css#L99.

Is this wanted 🤔?

**Comment by sindresorhus** [comment]
Yes, look at the original source: https://github.com/necolas/normalize.css#pre-code-kbd-samp
