### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by fridzema** [sindresorhus/modern-normalize#9]
Hello,
First of all, love this project!
 
I have a couple of personal suggestions tough:

- Maybe it is an idea to add an pre compiled minified version.
- Maybe a scss/less version.
- Add to common cdn providers (don't know it this is easy).
- Maybe for the people that live under a stone add it to bower.

**Comment by kutsan** [comment]
👎 for bower support. It's their shame not switching to npm already. I think creating extra complexity for an outdated manager is not worth it.

**Comment by fridzema** [comment]
@kutsan I know, but there a lot of people still using it (i am not one of those people).
In terms of making it [obsolete](https://github.com/sindresorhus/modern-normalize/issues/2) i think this must be widely available, also on these older "platforms".

**Comment by sindresorhus** [comment]
> Maybe it is an idea to add an pre compiled minified version.

I'm not interested in introducing a build-step, but if you know of a service that can automatically minify an URL to a CSS file, I'd be happy to add a link.

> Maybe a scss/less version.

I don't really see the point? They're just supersets of CSS. They can import CSS.

> Add to common cdn providers (don't know it this is easy).

Happy to link to reliable ones if someone submits. Like https://cdnjs.com

> Maybe for the people that live under a stone add it to bower.

Not going to happen, sorry.
