### ISSUE TITLE
Add `appearance: base-select`

### ISSUE THREAD

**Issue by atjn** [sindresorhus/modern-normalize#95]
It is now possible to change the appearance of the `select` element to a cross-browser standardized version, which can then be custom styled to match the design of a given website.

I think it would make sense to add this to `modern-normalize` such that the element is always rendered the same in all browsers:
```css
select {
  appearance: base-select;
}
```
It is also possible to do the same for the popup that is shown when you click on the element:
```css
::picker(select) {
  appearance: base-select;
}
```
..but I am not sure if that should be part of `modern-normalize`, since it is more of a browser/OS feature and you might want the picker to be well integrated with the OS. For example, the picker cannot be shown outside of the browser window if it has `base-select` enabled, and you might want and expect that to be possible.

At the moment, support is very experimental, but as soon as it ships in one browser, we could add it. The default select element is already different between all browsers and operating systems, so even if only one browser supports `base-select`, it would still be an improvement in overall consistency.

More information: https://open-ui.org/components/customizableselect/

**Comment by sindresorhus** [comment]
This would be outside the scope of modern-normalize.
